### ISSUE TITLE
yarn warnings (+ 1 error?)

### ISSUE THREAD

**Issue by ceich** [aws-samples/aws-mobile-appsync-events-starter-react#6]
Following the directions in `README.md`, I downloaded `AppSync.js` and ran `yarn`.  Results:
```
aws-mobile-appsync-events-starter-react aws: git:master $ yarn
yarn install v1.3.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > graphql-tag@2.8.0" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning " > react-apollo@2.0.4" has unmet peer dependency "apollo-client@^2.0.3".
warning "react-datepicker > eslint-plugin-import@2.9.0" has unmet peer dependency "eslint@2.x - 4.x".
warning "react-datepicker > eslint-plugin-node@5.2.1" has unmet peer dependency "eslint@>=3.1.0".
[4/4] 📃  Building fresh packages...
[-/4] ⠐ waiting...
[-/4] ⠐ waiting...
[-/4] ⠐ waiting...
[4/4] ⠐ fsevents: node-pre-gyp
warning Error running install script for optional dependency: "/Users/chriseich/Desktop/tools/aws-mobile-appsync-events-starter-react/node_modules/fsevents: Command failed.\nExit code: 1\nCommand: node install\nArguments: \nDirectory: /Users/chriseich/Desktop/tools/aws-mobile-appsync-events-starter-react/node_modules/fsevents\nOutput:\nnode-pre-gyp info it worked if it ends with ok\nnode-pre-gyp info using node-pre-gyp@0.6.39\nnode-pre-gyp info using node@9.5.0 | darwin | x64\nnode-pre-gyp info check checked for \"/Users/chriseich/Desktop/tools/aws-mobile-appsync-events-starter-react/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node\" (not found)\nnode-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz\nnode-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz\nnode-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@9.5.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp) \nnode-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz \nnode-pre-gyp ERR! build error \nnode-pre-gyp ERR! stack Error: Failed to execute 'node-gyp clean' (Error: spawn node-gyp ENOENT)\nnode-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/chriseich/Desktop/tools/aws-mobile-appsync-events-starter-react/node_modules/node-pre-gyp/lib/util/compile.js:77:29)\nnode-pre-gyp ERR! stack     at ChildProcess.emit (events.js:160:13)\nnode-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:207:12)\nnode-pre-gyp ERR! stack     at onErrorNT (internal/child_process.js:389:16)\nnode-pre-gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:152:19)\nnode-pre-gyp ERR! System Darwin 17.4.0\nnode-pre-gyp ERR! command \"/usr/local/Cellar/node/9.5.0/bin/node\" \"/Users/chriseich/Desktop/tools/aws-mobile-appsync-events-starter-react/node_modules/fsevents/node_modules/.bi✨  Done in 11.11s.
```

**Comment by elorzafe** [comment]
Hi @ceich I just tried this starter and didnt see that error. Did the starter works well for you?
